version: '3'

services:
    app:
        build:    { context: './', dockerfile: docker/Dockerfile }
        ports:    [ '8010:8010' ]
        env_file: .env
        links:    []
        volumes:
            - '~/.ssh:/root/.ssh'
            - '.:/app/:delegated'
            - 'composer:/root/.composer'
            - 'cache:/app/var/cache'

    nginx:
        image: nginx:1.13-alpine
        ports: [ '80:80', '443:443' ]
        links: [ app ]
        volumes:
            - './docker/vhost.conf:/etc/nginx/conf.d/default.conf'
            - '.:/app:delegated'

    mercure:
        image:    dunglas/mercure
        ports:    [ '8080:80' ]
        env_file: .env


volumes:
    cache:    ~
    composer: ~
