parameters:
    locale: 'fr'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Subscriber\SendChatMessageSubscriber:
        arguments:
            '$mercureHub': '%env(HUB_URL)%'


    App\Provider\JWTProvider:
        arguments:
            '$jwtKey': '%env(JWT_KEY)%'
